const ActionsConstants = {
  // Schedule Ride Actions
  SET_DATE: 'SET_DATE',
  SET_TIME: 'SET_TIME',

  //Profile Image
  SET_PROFILE_IMAGE: 'SET_PROFILE_IMAGE',
  REMOVE_PROFILE_IMAGE: 'REMOVE_PROFILE_IMAGE',

  //Account Details
  SET_ACCOUNT_FNAME: 'SET_ACCOUNT_FNAME',
  SET_ACCOUNT_LNAME: 'SET_ACCOUNT_LNAME',
  SET_ACCOUNT_NUMBER: 'SET_ACCOUNT_NUMBER',
  SET_ACCOUNT_EMAIL: 'SET_ACCOUNT_EMAIL',
  SET_ACCOUNT_PASSWORD: 'SET_ACCOUNT_PASSWORD',
  SET_ACCOUNT_COUNTRY_CODE: 'SET_ACCOUNT_COUNTRY_CODE',
  SET_FLAG: 'SET_FLAG',

  //Ride Information Actions
  SET_ORIGIN_NAME: 'SET_ORIGIN_NAME',
  SET_DESTINATION_NAME: 'SET_DESTINATION_NAME',
  SET_ORIGIN_COORD: 'SET_ORIGIN_COORD',
  SET_DESTINATION_COORD: 'SET_DESTINATION_COORD',

  //Payment Options Actions
  SET_CASH: 'SET_CASH',
  SET_PAYMENT_METHODS: 'SET_PAYMENT_METHODS',
  SET_PATMENT_ICON: 'SET_PAYMENT_ICONS',
};

export default ActionsConstants;
