const Screens = {
  SplashScreenViewModel: 'SplashScreenViewModel',
  OnBoardingViewModel: 'OnBoardingViewModel',
  UserprofileViewModel: 'UserprofileViewModel',
  HomeViewModel: 'HomeViewModel',
  WalletViewModel: 'WalletViewModel',
  HelpViewModel: 'HelpViewModel',
  MessagesViewModel: 'MessagesViewModel',
  SettingsViewModel: 'SettingsViewModel',
  LoginViewModel: 'LoginViewModel',
  EditAccountViewModel: 'EditAccountViewModel',
  SearchViewModel: 'SearchViewModel',
  TripViewModal: 'TripViewModal',
  CashPayViewModel: 'CashPayViewModel',
  PaymentOptionsViewModel: 'PaymentOptionsViewModel',
  AddPaymentViewModel: 'AddPaymentViewModel',
  AddCardViewModel: 'AddCardViewModel',
  SearchResultViewModel: 'SearchResultViewModel',
  ChooseRideViewModel: 'ChooseRideViewModel',
  ConfirmRideViewModel: 'ConfirmRideViewModel',
  CountryListViewModel: 'CountryListViewModel',
  PickupRideViewModel: 'PickupRideViewModel',
  StartTripViewModel: 'StartTripViewModel',
  TripViewDetails: 'TripViewDetails',
  HelpTripViewModel: 'HelpTrip',
  AccountHelpViewModel: 'AccountHelp',
  MoreScreenViewModel: 'MoreScreen',
  GuideScreenViewModel: 'GuideScreen',
  UberBusScreenViewModel: 'UberBusScreen',
  SigningUpScreenViewModel: 'SigningUpScreen',
  AccessibilityScreenViewModel: 'AccessibilityScreen',
  UberMoneyScreenViewModel: 'UberMoneyScreen',
  AlertMessageViewModel: 'AlertMessage',
};

export default Screens;
